name: starter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  effective_dart: ^1.3.0
  intl_utils: ^1.9.0
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/generated
